import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../common/prisma.service';
import { CreateUserDto, UpdateUserDto, UpdateProfileDto } from './dto';
import { User } from '@prisma/client';
import * as bcrypt from 'bcryptjs';
import * as crypto from 'crypto';

// fjern passord feltet fra user typen
type UserWithoutPassword = Omit<User, 'password'>;

@Injectable()
export class UsersService {
  constructor(private prisma: PrismaService) {}

  async create(createUserDto: CreateUserDto): Promise<UserWithoutPassword> {
    const { username, email, phoneNumber, password } = createUserDto;
    
    // Convert empty strings to null for optional fields
    const normalizedEmail = email && email.trim() !== '' ? email.trim() : null;
    const normalizedPhoneNumber = phoneNumber && phoneNumber.trim() !== '' ? phoneNumber.trim() : null;

    // Check if user already exists
    const existingUser = await this.prisma.user.findFirst({
      where: {
        OR: [
          { username },
          ...(normalizedEmail ? [{ email: normalizedEmail }] : []),
          ...(normalizedPhoneNumber ? [{ phoneNumber: normalizedPhoneNumber }] : []),
        ],
      },
    });

    if (existingUser) {
      if (existingUser.username === username) {
        throw new ConflictException('Username already exists');
      }
      if (normalizedEmail && existingUser.email === normalizedEmail) {
        throw new ConflictException('Email already exists');
      }
      if (normalizedPhoneNumber && existingUser.phoneNumber === normalizedPhoneNumber) {
        throw new ConflictException('Phone number already exists');
      }
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 12);

    // Create user (id is cuid generated by DB, inviteCode set after we know id)
    const user = await this.prisma.user.create({
      data: {
        username,
        email: normalizedEmail,
        phoneNumber: normalizedPhoneNumber,
        password: hashedPassword,
      },
    });

    // Now compute inviteCode using the actual user.id and store it
    const finalInviteCode = this.generateInviteCode(user.id);
    try {
      // Use loose typing until Prisma types are regenerated after migration
      await (this.prisma as any).user.update({
        where: { id: user.id },
        data: { inviteCode: finalInviteCode },
      });
    } catch (_) {
      // ignore if migration not applied yet
    }

    // Return user without password (... for å sre feltene ut, inneholder automatisk alle felt)
    const { password: _, ...userWithoutPassword } = user;
    return userWithoutPassword;
  }

  async findByUsername(username: string): Promise<User | null> {
    return this.prisma.user.findUnique({
      where: { username },
    });
  }

  async findByEmail(email: string): Promise<User | null> {
    return this.prisma.user.findUnique({
      where: { email },
    });
  }

  async findById(id: string): Promise<UserWithoutPassword | null> {
    const user = await this.prisma.user.findUnique({
      where: { id },
    });
    
    if (!user) return null;
    
    // Return user without password
    const { password: _, ...userWithoutPassword } = user;
    return userWithoutPassword;
  }

  async update(id: string, updateUserDto: UpdateUserDto): Promise<UserWithoutPassword> {
    const user = await this.prisma.user.findUnique({
      where: { id },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    const updatedUser = await this.prisma.user.update({
      where: { id },
      data: updateUserDto,
    });

    // Return user without password
    const { password: _, ...userWithoutPassword } = updatedUser;
    return userWithoutPassword;
  }

  async updateProfile(id: string, updateProfileDto: UpdateProfileDto): Promise<UserWithoutPassword> {
    const user = await this.prisma.user.findUnique({
      where: { id },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    // Check username uniqueness if username is being updated
    if (updateProfileDto.username && updateProfileDto.username !== user.username) {
      const existingUser = await this.prisma.user.findUnique({
        where: { username: updateProfileDto.username },
      });

      if (existingUser) {
        throw new ConflictException('Username already exists');
      }
    }

    // Check email uniqueness if email is being updated
    if (updateProfileDto.email !== undefined) {
      const normalizedEmail = updateProfileDto.email && updateProfileDto.email.trim() !== '' 
        ? updateProfileDto.email.trim() 
        : null;
      
      if (normalizedEmail && normalizedEmail !== user.email) {
        const existingUser = await this.prisma.user.findUnique({
          where: { email: normalizedEmail },
        });

        if (existingUser) {
          throw new ConflictException('Email already exists');
        }
      }
    }

    // Check phone number uniqueness if phone number is being updated
    if (updateProfileDto.phoneNumber !== undefined) {
      const normalizedPhoneNumber = updateProfileDto.phoneNumber && updateProfileDto.phoneNumber.trim() !== '' 
        ? updateProfileDto.phoneNumber.trim() 
        : null;
      
      if (normalizedPhoneNumber && normalizedPhoneNumber !== user.phoneNumber) {
        const existingUser = await this.prisma.user.findUnique({
          where: { phoneNumber: normalizedPhoneNumber },
        });

        if (existingUser) {
          throw new ConflictException('Phone number already exists');
        }
      }
    }

    // Build update data object
    const updateData: any = {};
    
    if (updateProfileDto.username) {
      updateData.username = updateProfileDto.username;
    }
    
    if (updateProfileDto.bio !== undefined) {
      // Allow empty string to clear bio
      updateData.bio = updateProfileDto.bio || null;
    }
    
    if (updateProfileDto.avatar !== undefined) {
      // Allow empty string to clear avatar
      updateData.avatar = updateProfileDto.avatar || null;
    }

    if (updateProfileDto.email !== undefined) {
      // Allow empty string to clear email
      const normalizedEmail = updateProfileDto.email && updateProfileDto.email.trim() !== '' 
        ? updateProfileDto.email.trim() 
        : null;
      updateData.email = normalizedEmail;
    }

    if (updateProfileDto.phoneNumber !== undefined) {
      // Allow empty string to clear phone number
      const normalizedPhoneNumber = updateProfileDto.phoneNumber && updateProfileDto.phoneNumber.trim() !== '' 
        ? updateProfileDto.phoneNumber.trim() 
        : null;
      updateData.phoneNumber = normalizedPhoneNumber;
    }

    const updatedUser = await this.prisma.user.update({
      where: { id },
      data: updateData,
    });

    // Return user without password
    const { password: _, ...userWithoutPassword } = updatedUser;
    return userWithoutPassword;
  }

  async updateOnlineStatus(id: string, isOnline: boolean): Promise<{ success: boolean; message: string }> {
    await this.prisma.user.update({
      where: { id },
      data: {
        isOnline,
        lastSeen: new Date(),
      },
    });
    
    return {
      success: true,
      message: `User status updated to ${isOnline ? 'online' : 'offline'}`,
    };
  }

  async validatePassword(password: string, hashedPassword: string): Promise<boolean> {
    return bcrypt.compare(password, hashedPassword);
  }

  async searchUsers(username: string): Promise<UserWithoutPassword[]> {
    const users = await this.prisma.user.findMany({
      where: {
        username: {
          contains: username,
          mode: 'insensitive',
        },
      },
      select: {
        id: true,
        username: true,
        email: true,
        phoneNumber: true,
        inviteCode: true,
        avatar: true,
        bio: true,
        isOnline: true,
        lastSeen: true,
        showOnlineStatus: true,
        createdAt: true,
        updatedAt: true,
        // Exclude password field
      },
      take: 10, // Limit to 10 results
      orderBy: {
        username: 'asc',
      },
    });

    return users as UserWithoutPassword[];
  }

  async getUserFriends(userId: string): Promise<UserWithoutPassword[]> {
    const friendships = await this.prisma.friendship.findMany({
      where: {
        userId,
        status: 'ACCEPTED',
      },
      include: {
        friend: {
          select: {
            id: true,
            username: true,
            email: true,
            phoneNumber: true,
            inviteCode: true,
            avatar: true,
            bio: true,
            isOnline: true,
            lastSeen: true,
            showOnlineStatus: true,
            createdAt: true,
            updatedAt: true,
            // Exclude password field
          },
        },
      },
      orderBy: {
        updatedAt: 'desc',
      },
    });

    return friendships.map(friendship => friendship.friend as UserWithoutPassword);
  }

  async getMutualFriendsCount(userId1: string, userId2: string): Promise<number> {
    // Get friends of user1
    const user1Friendships = await this.prisma.friendship.findMany({
      where: {
        userId: userId1,
        status: 'ACCEPTED',
      },
      select: {
        friendId: true,
      },
    });
    const user1FriendIds = user1Friendships.map(f => f.friendId);

    // Get friends of user2
    const user2Friendships = await this.prisma.friendship.findMany({
      where: {
        userId: userId2,
        status: 'ACCEPTED',
      },
      select: {
        friendId: true,
      },
    });
    const user2FriendIds = user2Friendships.map(f => f.friendId);

    // Find mutual friends
    const mutualFriends = user1FriendIds.filter(id => user2FriendIds.includes(id));
    return mutualFriends.length;
  }

  async getSuggestedUsers(userId: string, limit: number = 10): Promise<Array<UserWithoutPassword & { mutualFriendsCount: number }>> {
    // Get current user's friends
    const userFriendships = await this.prisma.friendship.findMany({
      where: {
        userId,
        status: 'ACCEPTED',
      },
      select: {
        friendId: true,
      },
    });
    const userFriendIds = userFriendships.map(f => f.friendId);
    userFriendIds.push(userId); // Exclude self

    // Get all users except current user and their friends
    const allUsers = await this.prisma.user.findMany({
      where: {
        id: {
          notIn: userFriendIds,
        },
      },
      select: {
        id: true,
        username: true,
        email: true,
        phoneNumber: true,
        inviteCode: true,
        avatar: true,
        bio: true,
        isOnline: true,
        lastSeen: true,
        showOnlineStatus: true,
        createdAt: true,
        updatedAt: true,
      },
      take: limit * 2, // Get more to filter and sort
    });

    // Calculate mutual friends for each user
    const usersWithMutualFriends = await Promise.all(
      allUsers.map(async (user) => {
        const mutualFriendsCount = await this.getMutualFriendsCount(userId, user.id);
        return {
          ...user,
          mutualFriendsCount,
        };
      })
    );

    // Sort by mutual friends count (descending) and take limit
    return usersWithMutualFriends
      .sort((a, b) => b.mutualFriendsCount - a.mutualFriendsCount)
      .slice(0, limit);
  }

  private generateInviteCode(userId: string): string {
    const secret = process.env.INVITE_CODE_SECRET || process.env.JWT_SECRET || 'fallback-secret-change-me';
    const hmac = crypto.createHmac('sha256', secret).update(userId).digest('hex');
    return hmac.substring(0, 8).toUpperCase();
  }

  // Privacy Settings Methods
  async getPrivacySettings(userId: string): Promise<{
    global: { showOnlineStatus: boolean; locationSharingEnabled: boolean };
    friends: Array<{ friendId: string; hideOnlineStatus: boolean }>;
  }> {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { showOnlineStatus: true },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    const friendSettings = await this.prisma.userPrivacySettings.findMany({
      where: { userId },
      select: { targetUserId: true, hideOnlineStatus: true },
    });

    // Get locationSharingEnabled from user (using type assertion since Prisma client may not be regenerated)
    const fullUser = await this.prisma.user.findUnique({
      where: { id: userId },
    });
    const locationSharingEnabled = (fullUser as any)?.locationSharingEnabled || false;

    return {
      global: { 
        showOnlineStatus: user.showOnlineStatus,
        locationSharingEnabled,
      },
      friends: friendSettings.map(setting => ({
        friendId: setting.targetUserId,
        hideOnlineStatus: setting.hideOnlineStatus,
      })),
    };
  }

  async updateGlobalOnlineStatus(userId: string, showOnlineStatus: boolean): Promise<{ success: boolean; message: string }> {
    await this.prisma.user.update({
      where: { id: userId },
      data: { showOnlineStatus },
    });

    return {
      success: true,
      message: `Global online status visibility updated to ${showOnlineStatus ? 'visible' : 'hidden'}`,
    };
  }

  async updateFriendOnlineStatusVisibility(
    userId: string, 
    targetUserId: string, 
    hideOnlineStatus: boolean
  ): Promise<{ success: boolean; message: string }> {
    await this.prisma.userPrivacySettings.upsert({
      where: {
        userId_targetUserId: {
          userId,
          targetUserId,
        },
      },
      update: { hideOnlineStatus },
      create: {
        userId,
        targetUserId,
        hideOnlineStatus,
      },
    });

    return {
      success: true,
      message: `Online status visibility for friend updated to ${hideOnlineStatus ? 'hidden' : 'visible'}`,
    };
  }

  async getFriendOnlineStatusVisibility(userId: string, targetUserId: string): Promise<boolean> {
    const setting = await this.prisma.userPrivacySettings.findUnique({
      where: {
        userId_targetUserId: {
          userId,
          targetUserId,
        },
      },
    });

    return setting?.hideOnlineStatus || false;
  }

  async canUserSeeOnlineStatus(viewerId: string, targetUserId: string): Promise<boolean> {
    // Check if target user has global online status enabled
    const targetUser = await this.prisma.user.findUnique({
      where: { id: targetUserId },
      select: { showOnlineStatus: true },
    });

    if (!targetUser || !targetUser.showOnlineStatus) {
      return false;
    }

    // Check if target user has hidden their status from the viewer
    const privacySetting = await this.prisma.userPrivacySettings.findUnique({
      where: {
        userId_targetUserId: {
          userId: targetUserId,
          targetUserId: viewerId,
        },
      },
    });

    return !privacySetting?.hideOnlineStatus;
  }

  async updateLocationSharing(userId: string, locationSharingEnabled: boolean): Promise<{ success: boolean; message: string }> {
    await this.prisma.user.update({
      where: { id: userId },
      data: { locationSharingEnabled } as any,
    });

    return {
      success: true,
      message: `Location sharing ${locationSharingEnabled ? 'enabled' : 'disabled'}`,
    };
  }
}
