import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../common/prisma.service';
import { CreateUserDto, UpdateUserDto } from './dto';
import { User } from '@prisma/client';
import * as bcrypt from 'bcryptjs';
import * as crypto from 'crypto';

// fjern passord feltet fra user typen
type UserWithoutPassword = Omit<User, 'password'>;

@Injectable()
export class UsersService {
  constructor(private prisma: PrismaService) {}

  async create(createUserDto: CreateUserDto): Promise<UserWithoutPassword> {
    const { username, email, phoneNumber, password } = createUserDto;
    
    // Convert empty strings to null for optional fields
    const normalizedEmail = email && email.trim() !== '' ? email.trim() : null;
    const normalizedPhoneNumber = phoneNumber && phoneNumber.trim() !== '' ? phoneNumber.trim() : null;

    // Check if user already exists
    const existingUser = await this.prisma.user.findFirst({
      where: {
        OR: [
          { username },
          ...(normalizedEmail ? [{ email: normalizedEmail }] : []),
          ...(normalizedPhoneNumber ? [{ phoneNumber: normalizedPhoneNumber }] : []),
        ],
      },
    });

    if (existingUser) {
      if (existingUser.username === username) {
        throw new ConflictException('Username already exists');
      }
      if (normalizedEmail && existingUser.email === normalizedEmail) {
        throw new ConflictException('Email already exists');
      }
      if (normalizedPhoneNumber && existingUser.phoneNumber === normalizedPhoneNumber) {
        throw new ConflictException('Phone number already exists');
      }
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 12);

    // Create user (id is cuid generated by DB, inviteCode set after we know id)
    const user = await this.prisma.user.create({
      data: {
        username,
        email: normalizedEmail,
        phoneNumber: normalizedPhoneNumber,
        password: hashedPassword,
      },
    });

    // Now compute inviteCode using the actual user.id and store it
    const finalInviteCode = this.generateInviteCode(user.id);
    try {
      // Use loose typing until Prisma types are regenerated after migration
      await (this.prisma as any).user.update({
        where: { id: user.id },
        data: { inviteCode: finalInviteCode },
      });
    } catch (_) {
      // ignore if migration not applied yet
    }

    // Return user without password (... for å sre feltene ut, inneholder automatisk alle felt)
    const { password: _, ...userWithoutPassword } = user;
    return userWithoutPassword;
  }

  async findByUsername(username: string): Promise<User | null> {
    return this.prisma.user.findUnique({
      where: { username },
    });
  }

  async findByEmail(email: string): Promise<User | null> {
    return this.prisma.user.findUnique({
      where: { email },
    });
  }

  async findById(id: string): Promise<UserWithoutPassword | null> {
    const user = await this.prisma.user.findUnique({
      where: { id },
    });
    
    if (!user) return null;
    
    // Return user without password
    const { password: _, ...userWithoutPassword } = user;
    return userWithoutPassword;
  }

  async update(id: string, updateUserDto: UpdateUserDto): Promise<UserWithoutPassword> {
    const user = await this.prisma.user.findUnique({
      where: { id },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    const updatedUser = await this.prisma.user.update({
      where: { id },
      data: updateUserDto,
    });

    // Return user without password
    const { password: _, ...userWithoutPassword } = updatedUser;
    return userWithoutPassword;
  }

  async updateOnlineStatus(id: string, isOnline: boolean): Promise<void> {
    await this.prisma.user.update({
      where: { id },
      data: {
        isOnline,
        lastSeen: new Date(),
      },
    });
  }

  async validatePassword(password: string, hashedPassword: string): Promise<boolean> {
    return bcrypt.compare(password, hashedPassword);
  }

  async searchUsers(username: string): Promise<UserWithoutPassword[]> {
    const users = await this.prisma.user.findMany({
      where: {
        username: {
          contains: username,
          mode: 'insensitive',
        },
      },
      select: {
        id: true,
        username: true,
        email: true,
        phoneNumber: true,
        inviteCode: true,
        avatar: true,
        isOnline: true,
        lastSeen: true,
        createdAt: true,
        updatedAt: true,
        // Exclude password field
      },
      take: 10, // Limit to 10 results
      orderBy: {
        username: 'asc',
      },
    });

    return users;
  }
  private generateInviteCode(userId: string): string {
    const secret = process.env.INVITE_CODE_SECRET || process.env.JWT_SECRET || 'fallback-secret-change-me';
    const hmac = crypto.createHmac('sha256', secret).update(userId).digest('hex');
    return hmac.substring(0, 8).toUpperCase();
  }
}
